# Generated by Django 4.2.2 on 2023-07-02 02:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight_reservation",
            name="flightClass",
            field=models.CharField(
                choices=[("Economy", "Economy"), ("Business", "Business")],
                default="Economy",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="traveling_date",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 7, 2, 2, 4, 8, 894749, tzinfo=datetime.timezone.utc
                        )
                    )
                ],
                verbose_name="travelingDate",
            ),
        ),
    ]
