# Generated by Django 4.2.2 on 2023-07-02 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0002_flight_reservation_flightclass_and_more"),
        ("flight", "0003_alter_flight_traveling_date"),
    ]

    operations = []
