# Generated by Django 4.2.1 on 2023-07-02 13:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_merge_20230702_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='traveling_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 7, 2, 13, 13, 52, 347263, tzinfo=datetime.timezone.utc))], verbose_name='travelingDate'),
        ),
    ]
