# Generated by Django 4.2.2 on 2023-07-02 18:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0005_alter_flight_traveling_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight_reservation",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="flight_reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="traveling_date",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 7, 2, 18, 20, 10, 340612, tzinfo=datetime.timezone.utc
                        )
                    )
                ],
                verbose_name="travelingDate",
            ),
        ),
    ]
