# Generated by Django 4.2.2 on 2023-07-04 01:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0009_alter_flight_traveling_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight_reservation",
            name="expiration_time",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2023, 7, 6, 1, 38, 53, 450436, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="traveling_date",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 7, 4, 1, 38, 53, 450136, tzinfo=datetime.timezone.utc
                        )
                    )
                ],
                verbose_name="travelingDate",
            ),
        ),
    ]
