<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-30 14:24
=======
# Generated by Django 4.2.1 on 2023-06-30 01:11
>>>>>>> b48d62ab3b7545ebfdc113262ddce8efad3164d2

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_alter_flight_traveling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='traveling_date',
<<<<<<< HEAD
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 30, 14, 24, 14, 243664, tzinfo=datetime.timezone.utc))], verbose_name='travelingDate'),
=======
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 30, 1, 11, 4, 660948, tzinfo=datetime.timezone.utc))], verbose_name='travelingDate'),
>>>>>>> b48d62ab3b7545ebfdc113262ddce8efad3164d2
        ),
    ]
