# Generated by Django 4.2.1 on 2023-06-30 01:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_alter_flight_traveling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='traveling_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 30, 1, 11, 4, 660948, tzinfo=datetime.timezone.utc))], verbose_name='travelingDate'),
        ),
    ]
