# Generated by Django 4.2.2 on 2023-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_rename_flight_id_flight_reservation_flight_and_more'),
        ('flight', '0019_alter_flight_traveling_date'),
    ]

    operations = [
    ]
