# Generated by Django 4.2.2 on 2023-06-25 13:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0020_merge_20230625_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='traveling_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 25, 13, 41, 58, 25805, tzinfo=datetime.timezone.utc))], verbose_name='travelingDate'),
        ),
    ]
