# Generated by Django 4.2.1 on 2023-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
