# Generated by Django 4.2.1 on 2023-06-29 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_hotel_avg_rating'),
        ('hotelReview', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotelreview',
            unique_together={('user', 'hotel')},
        ),
    ]
