# Generated by Django 4.2.1 on 2023-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
