# Generated by Django 4.2 on 2023-06-25 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='latitude'),
        ),
    ]
