# Generated by Django 4.2.1 on 2023-06-22 14:44

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('image', models.FileField(blank=True, null=True, upload_to='user_images')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should contain only digits.', regex='^\\d{1,20}$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('street_name', models.CharField(max_length=255)),
                ('building_no', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
