# Generated by Django 4.2 on 2023-06-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelReservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayreservation',
            name='room_type',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('D', 'Double')], max_length=1, null=True),
        ),
    ]
