# Generated by Django 4.2.2 on 2023-07-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotelReservation", "0003_stayreservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stayreservation",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
